// Code generated by `just build-runners`; DO NOT EDIT.
package rundaemon

// This file stamps RunnerVersion (declared in bootstrap.go, default "dev")
// with the content-hash version of the embedded runner binaries — the SAME
// hash the runner's main.version carries (ldflags in build-runners). Keeping
// the two in lockstep is the bootstrap version-sync invariant; a normal
// `go build ./cmd/shellkit` picks up this hash with no special ldflags.
func init() { RunnerVersion = "bb82f4a10429" }
