package sshconn

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/caoer/shellkit/internal/inventory"
)

func providerLabel(p string) string {
	if len(p) == 0 {
		return "Unknown"
	}
	return strings.ToUpper(p[:1]) + p[1:]
}

func identityFileLine(identity string) string {
	if identity == "" {
		return ""
	}
	if strings.Contains(identity, "/") {
		return fmt.Sprintf("  IdentityFile %s", identity)
	}
	return fmt.Sprintf("  IdentityFile ~/.ssh/keys/%s", identity)
}

func descComment(s inventory.Server) string {
	var parts []string
	if s.Account != "" {
		parts = append(parts, "@"+s.Account)
	}
	if s.Plan != "" {
		parts = append(parts, "("+s.Plan+")")
	}
	if s.Location != "" {
		parts = append(parts, s.Location)
	}
	if s.Expires != "" {
		parts = append(parts, "["+s.Expires+"]")
	}
	if s.IPv6 != "" {
		parts = append(parts, "<"+s.IPv6+">")
	}
	if s.Notes != "" {
		parts = append(parts, s.Notes)
	}
	if len(parts) == 0 {
		return ""
	}
	return "#_Desc " + strings.Join(parts, " ")
}

func GenerateSSHConfig(servers []inventory.Server, w io.Writer) {
	// Global defaults
	fmt.Fprintln(w, "# SSH Configuration — generated by shellkit generate-configs")
	fmt.Fprintln(w, "# Source: shellkit inventory (.nix hosts attset)")
	fmt.Fprintln(w, "# Vim: set foldmethod=marker")
	fmt.Fprintln(w)

	fmt.Fprintln(w, "# {{{ Global Defaults")
	fmt.Fprintln(w, "Host *")
	fmt.Fprintln(w, "  IgnoreUnknown UseKeychain")
	fmt.Fprintln(w, "  AddKeysToAgent yes")
	fmt.Fprintln(w, "  UseKeychain yes")
	fmt.Fprintln(w, "  StrictHostKeyChecking no")
	fmt.Fprintln(w, "  UserKnownHostsFile /dev/null")
	fmt.Fprintln(w, "  IdentitiesOnly yes")
	fmt.Fprintln(w, "  LogLevel ERROR")
	fmt.Fprintln(w, "  ServerAliveInterval 60")
	fmt.Fprintln(w, "  ServerAliveCountMax 3")
	fmt.Fprintln(w, "  ControlMaster no")
	fmt.Fprintln(w, "# }}}")

	// Group by provider
	groups := map[string][]inventory.Server{}
	for _, s := range servers {
		if s.IsOrb() {
			continue
		}
		if s.ResolvedIP() == "" || s.User == "" {
			continue
		}
		groups[s.Provider] = append(groups[s.Provider], s)
	}

	// Sort providers
	providers := make([]string, 0, len(groups))
	for p := range groups {
		providers = append(providers, p)
	}
	sort.Strings(providers)

	for _, provider := range providers {
		srvs := groups[provider]
		sort.Slice(srvs, func(i, j int) bool {
			return srvs[i].SSHAlias < srvs[j].SSHAlias
		})

		fmt.Fprintln(w)
		fmt.Fprintf(w, "# {{{ %s\n", providerLabel(provider))
		fmt.Fprintln(w)

		for _, s := range srvs {
			resolved := s.ResolvedIP()
			fmt.Fprintf(w, "Host %s\n", s.SSHAlias)
			fmt.Fprintf(w, "  HostName %s\n", resolved)
			port := s.PortFor(resolved)
			if port != 22 {
				fmt.Fprintf(w, "  Port %d\n", port)
			}
			fmt.Fprintf(w, "  User %s\n", s.DisplayUser())
			if line := identityFileLine(s.Identity); line != "" {
				fmt.Fprintln(w, line)
			}
			fmt.Fprintln(w, "  IdentitiesOnly yes")
			if s.ProxyJump != "" {
				fmt.Fprintf(w, "  ProxyJump %s\n", s.ProxyJump)
			}
			fmt.Fprintln(w, "  ControlMaster auto")
			fmt.Fprintf(w, "  ControlPath ~/.ssh/sockets/%%r@%s-%%p\n", s.SSHAlias)
			fmt.Fprintln(w, "  ControlPersist 600")
			if desc := descComment(s); desc != "" {
				fmt.Fprintf(w, "  %s\n", desc)
			}
			fmt.Fprintln(w)
		}

		fmt.Fprintln(w, "# }}}")
	}
}
